<Project>
  <PropertyGroup>
    <Nullable>disable</Nullable>
    <!--App版本--><!--
    <AppVersion>2.4.0</AppVersion>
    --><!--Avalonia版本--><!--
    <AvaloniaVersion>11.3.11</AvaloniaVersion>
    --><!--FzLib版本（版本号统一在 Directory.Packages.props 管理）-->
    <!--是否指定调试时的输出目录，以及指定目录位置-->
    <SpecialOutputDir>true</SpecialOutputDir>
    <OutputDir>..\Generation</OutputDir>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <SatelliteResourceLanguages>zh-cn</SatelliteResourceLanguages>
  </PropertyGroup>

  <!--指定bin目录和obj目录位置，排除临时编译项目-->
  <PropertyGroup Condition="'$(SpecialOutputDir)' == 'true' and !$(MSBuildProjectName.EndsWith('_wpftmp'))">
    <OutputPath>$(OutputDir)\bin\$(Configuration)\$(MSBuildProjectName)</OutputPath>
    <BaseIntermediateOutputPath>$(OutputDir)\obj\$(Configuration)\$(MSBuildProjectName)</BaseIntermediateOutputPath>
  </PropertyGroup>

</Project>
